version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

volumes:
  models_data:
  app_data: 