version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: yahoo-nlp
    container_name: yahoo-nlp-service
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - USE_CUDA=0
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    restart: unless-stopped

volumes:
  models_data:
  app_data: 